# -*- coding: utf-8 -*-
"""Endoding&Decoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HlYTmqhPFNsazeDcvQ1Ib4dxfFid3GRy
"""

pip install tkinter
pip install base64

import tkinter as tk
from tkinter import filedialog
import base64

# For encoding
def encode_file():
    file_path = filedialog.askopenfilename()
    if file_path:
        with open(file_path, 'rb') as file:
            file_content = file.read()
            encoded_content = base64.b64encode(file_content)

        save_path = filedialog.asksaveasfilename(defaultextension='.txt')
        if save_path:
            with open(save_path, 'wb') as file:
                file.write(encoded_content)

# For decoding
def decode_file():
    file_path = filedialog.askopenfilename()
    if file_path:
        with open(file_path, 'rb') as file:
            file_content = file.read()
            decoded_content = base64.b64decode(file_content)

        save_path = filedialog.asksaveasfilename(defaultextension='.txt')
        if save_path:
            with open(save_path, 'wb') as file:
                file.write(decoded_content)

# Create the Tkinter window
window = tk.Tk()

# Create buttons for encoding and decoding
encode_button = tk.Button(window, text='Encode', command=encode_file)
encode_button.pack()

decode_button = tk.Button(window, text='Decode', command=decode_file)
decode_button.pack()

# Run the Tkinter event loop
window.mainloop()